### ISSUE TITLE
Nonstandard version string - please use YYYY-MM or YYYY-MM-DD

### ISSUE THREAD

**Issue by cthoyt** [enpadasi/Ontology-for-Nutritional-Studies#25]
The latest version of ONS is `June 2021 release`. While this field is _technically_ free text, it's much more useful for the community if you follow a standardized format that's computer-parsable. I'd suggest changing to 2021-06 for this releases, and using the same scheme in the future

**Comment by cthoyt** [comment]
It appears that this project previously used semantic versioning. Was there a particular motivation for changing?

**Comment by FrancescoVit** [comment]
Thank you for the comment @cthoyt 
Honestly, there were no particular motivation for changing. I saw other ontologies using "easier" versioning based on release date, but I see that there's the risk of making more confusion, and to loose standard. 

We will go back to a point release system with next release (should be in July), as we had prior to this last release (I think this would also be better for multiple release during same month).

**Comment by ddooley** [comment]
I personally am attracted to version/release information that indicates information about release date down to the day (that is common in OBOFoundry).  But I understand if you want v1.0 1.1 etc.  That is accomplished as you have it now by putting the "latest release" id.  I like including release date in title though e.g. "ONS Release 2021-08-23".  Otherwise one has to read the fine print about when in the past a version is concocted.  Just a personal thought.  (For FoodOn, I think we'll switch to a date-based release. The incremental id's so far were just about getting the basic pieces into place before a "v1" but I think we're just about there now.)

**Comment by cthoyt** [comment]
@FrancescoVit it doesn't look like the new files actually made a fix for this - having the text "Release version" as part of the version string still is a problem
<img width="1232" alt="Screen Shot 2021-08-23 at 16 16 49" src="https://user-images.githubusercontent.com/5069736/130462975-ffd18d79-c533-4cd7-aacf-ae1eb9a02cb6.png">
