### ISSUE TITLE
Define and add class "Palatability"

### ISSUE THREAD

**Issue by AnaReisCosta** [enpadasi/Ontology-for-Nutritional-Studies#26]
Add a class:

**label** Palatability
**superclass** information content entity
**definition** food property that leads to the stimulation of the dopamine reward pathway. It is usually related to fats and sugars

**Rationale:** "Food choices" [ONS:0000132] are driven by the "food choice management process" [ONS:0000128], which in turn is influenced by a multitude of factors defined as "determinant of diet" [ONS:0000131]. Among these, there is the appeal to eat very tasty foods because of the positive effect they exert on the dopamine reward circuitry. In this way, foods rich in highly palatable ingredients such as simple sugars and fats might be preferred to healthier nutrient-dense alternatives.

**Comment by FrancescoVit** [comment]
**label** Palatability [ONS:0000133]
**superclass** information content entity
**definition** the palatability of a food refers to its capacity of triggering a reward (i.e. hedonic reward, or pleasure, via a stimulation of the dopamine reward pathway) upon consumption. This property can be related to various aspects of food, usually related to fats and sugars content.
**rdfs:seeAlso** https://en.wikipedia.org/wiki/Palatability
**example of usage**  "Food choices" [ONS:0000132] are driven by the "food choice management process" [ONS:0000128], which in turn is influenced by a multitude of factors defined as "determinant of diet" [ONS:0000131]. Among these, there is the appeal to eat very tasty foods because of the positive effect they exert on the dopamine reward circuitry. In this way, foods rich in highly palatable ingredients such as simple sugars and fats might be preferred to healthier nutrient-dense alternatives.
