### ISSUE TITLE
Define and add class "Industrialized diet"

### ISSUE THREAD

**Issue by AnaReisCosta** [enpadasi/Ontology-for-Nutritional-Studies#29]
Add a class:

**label** Industrialized diet
**superclass** information content entity
**definition** Dietary pattern resulting from the lifestyle adaptation following the industrial revolution. It is often associated with western countries, even though it can be verified in other geographic areas.

Rationale: We propose the introduction of a new term in the literature that replaces "Western diet". We noticed there is great heterogeneity in the application of the "Western diet" concept in the literature and that it might often be wrongly associated with the diet of a geographic location, even though it has a broader distribution. Taking into consideration this lifestyle is considered the result of the Industrial Revolution, we believe that "industrialized" is a better adjective than "western". In this way, we want to introduce the "Industrialized diet" class as an exact synonym to the "Western diet" class. Moreover, the "Industrialized diet" is in opposition with the "Rural diet" class, which characterizes the dietary pattern in areas where the industrial revolution had less impact. #28 #27

**Comment by ddooley** [comment]
Perhaps close the other issue for "western diet" then? And have "western diet" be a related or exact synonym?

**Comment by FrancescoVit** [comment]
Indeed, there is the need of a single class/concept, using "exact synonym" and "editor preferred label" to direct. In literature the "western diet" term is widely used, but have a strong gographical link

**Comment by FrancescoVit** [comment]
Add a class:

**label** globalized diet [ONS:1000065]
**superclass** diet by nutritional composition [ONS:1000005]
**definition** the diet resulting from the lifestyle adaptation following the industrial revolution. It is often associated with western countries, but is increasingly becoming adopted also in other geographic areas. It is known to be rich in red and processed meats, sweets, fried foods, and refined grains while being poor in fruits, vegetables, legumes, fish, poultry, and whole grains. In terms of micronutrients, this diet is usually rich in salt, yet poor in other minerals and vitamins, whereas in terms of fats, it is high in saturated and trans-fatty acids, and low in mono- and polyunsaturated fatty acids. Its fibre and complex carbohydrates contents are also very low due to the high consumption of refined sugars instead of whole-grain foods.
** editor note** "Western diet" synonym of this concept has a wider use in the literature, nevertheless it imply a misleading association to specific geographic location, even though it has a broader distribution. Another possible synonym, taking into consideration that this lifestyle is considered the result of the Industrial Revolution, is "industrialized diet"
**has exact synonym" western diet; industrialized diet

**Comment by FrancescoVit** [comment]
Add a class:

**label** globalized diet dietary pattern [ONS:2000044]
**superclass** dietary pattern  by nutritional composition [ONS:2000005]
**definition** a dietary pattern that define the quantity, variety or combination of different food in a globalized diet
